cluster_name             = "yen-test"
region                   = "eu-west-1"
logs_group               = "/ecs/yen-test"
nginx_ecr_repository_url = "<account number>.dkr.ecr.eu-west-1.amazonaws.com/yen-nginx:latest"
php_ecr_repository_url   = "<account number>.dkr.ecr.eu-west-1.amazonaws.com/yen-php:latest"
